<a href="https://colab.research.google.com/github/Mahajan2023/DS-projects/blob/Masters/Decision_Tree_and_Random_Forest_%2CNaive_Bayes%2C_SVM_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
dataset=pd.read_csv('/content/Social_Network_Ads.csv')

In [3]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset.corr()

User ID       Age  EstimatedSalary  Purchased
User ID          1.000000 -0.000721         0.071097   0.007120
Age             -0.000721  1.000000         0.155238   0.622454
EstimatedSalary  0.071097  0.155238         1.000000   0.362083
Purchased        0.007120  0.622454         0.362083   1.000000

In [5]:
dataset.drop(['User ID','Gender'],inplace= True,axis=1)

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
scaler=StandardScaler()

In [9]:
scaler.fit(dataset.drop('Purchased',axis=1))

StandardScaler()

In [10]:
scaled_fetures=scaler.transform(dataset.drop('Purchased',axis=1))

In [11]:
scaled_fetures

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059],
       [-1.01769239, -0.34481683],
       [-1.01769239,  0.41866944],
       [-0.54012675,  2.35674998],
       [-1.20871865, -1.07893824],
       [-0.25358736, -0.13926283],
       [-1.11320552,  0.30121002],
       [-1.11320552, -0.52100597],
       [-1.6862843 ,  0.47739916],
       [-0.54012675, -1.51941109],
       [-1.87731056,  0.35993973],
       [-0.82666613,  0.30121002],
       [ 0.89257019, -1.3138571 ],
       [ 0.70154394, -1.28449224],
       [ 0.79705706, -1.22576253],
       [ 0.98808332, -1.19639767],
       [ 0.70154394, -1.40195167],
       [ 0.89257019, -0.60910054],
       [ 0.98808332, -0.84401939],
       [ 0.70154394, -1.40195167],
       [ 0.79705706, -1.37258681],
       [ 0.89257019, -1.46068138],
       [ 1.08359645, -1.22576253],
       [ 0.89257019, -1.16703281],
       [-0.82666613,

In [12]:
df=pd.DataFrame(scaled_fetures,columns=['Age','EstimateSalary'])

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(df,dataset['Purchased'],test_size=0.30,random_state=40)

In [15]:
x_train.shape

(280, 2)

In [16]:
x_test.shape

(120, 2)

In [17]:
y_train.shape

(280,)

In [18]:
y_test.shape

(120,)

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
DTC = DecisionTreeClassifier()

In [21]:
DTC.fit(x_train,y_train)

DecisionTreeClassifier()

In [22]:
pred=DTC.predict(x_test)

In [23]:
from sklearn.metrics import confusion_matrix, classification_report

In [24]:
print(confusion_matrix(y_test,pred))

[[69  8]
 [ 9 34]]


In [25]:
correct=69+34

In [26]:
(correct/120)*100

85.83333333333333

In [ ]:
# Random Forest

Random Forest
    It is a classifiaction algorithm which will take the help from the decision tree on the dataset and will take the average of the outcomes of decision tree to help for improving the accuracy of the prediction.

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
rfc = RandomForestClassifier(n_estimators=200)

In [29]:
rfc.fit(x_train,y_train)

RandomForestClassifier(n_estimators=200)

In [30]:
rfc_pred= rfc.predict(x_test)

In [31]:
from sklearn.metrics import confusion_matrix, classification_report

In [32]:
print(confusion_matrix(y_test,rfc_pred))

[[73  4]
 [ 6 37]]


In [33]:
correct=71+36

In [34]:
(correct/120)*100

89.16666666666667

In [35]:
# Naive Bayes

Its work on prior proabilty

In [43]:
from sklearn.naive_bayes import GaussianNB # it follows gaussian type distibution

In [44]:
GNB = GaussianNB()

In [45]:
GNB.fit(x_train,y_train)

GaussianNB()

In [46]:
y_pred=GNB.predict(x_test)

In [57]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [58]:
acc=accuracy_score(y_test,y_pred)

In [59]:
acc

0.875

In [60]:
acc*100

87.5

In [61]:
# Support Vectore Mechine lerning Model

In [48]:
from sklearn.svm import SVC

In [49]:
classifier=SVC()

In [50]:
classifier.fit(x_train,y_train)

SVC()

In [51]:
pred=classifier.predict(x_test)

In [52]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [53]:
acc=accuracy_score(y_test,pred)

In [55]:
acc

0.9166666666666666

In [56]:
acc*100

91.66666666666666