<a href="https://colab.research.google.com/github/Mahajan2023/DS-projects/blob/Masters/Natural_language_Processing_(NLP).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Natural language Processing (NLP)

In [ ]:
loved the food 
food was lovely 
loved the ambiance and food was testy 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df= pd.read_csv('/content/Restaurant_Reviews.tsv',delimiter='\t')

In [3]:
df

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Review  1000 non-null   object
 1   Liked   1000 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 15.8+ KB


In [5]:
import nltk # natural lenguage tool kit

In [6]:
from nltk.corpus import stopwords

In [7]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [8]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [9]:
df.head(20)

Review  Liked
0                            Wow... Loved this place.      1
1                                  Crust is not good.      0
2           Not tasty and the texture was just nasty.      0
3   Stopped by during the late May bank holiday of...      1
4   The selection on the menu was great and so wer...      1
5      Now I am getting angry and I want my damn pho.      0
6               Honeslty it didn't taste THAT fresh.)      0
7   The potatoes were like rubber and you could te...      0
8                           The fries were great too.      1
9                                      A great touch.      1
10                           Service was very prompt.      1
11                                 Would not go back.      0
12  The cashier had no care what so ever on what I...      0
13  I tried the Cape Cod ravoli, chicken, with cra...      1
14  I was disgusted because I was pretty sure that...      0
15  I was shocked because no signs indicate cash o...      0
16                                Highly recommended.      1
17             Waitress was a little slow in service.      0
18  This place is not worth your time, let alone V...      0
19                               did not like at all.      0

In [10]:
import re

In [11]:
re.sub('[^a-zA-Z]',' ',df['Review'][2]).lower().split()

['not', 'tasty', 'and', 'the', 'texture', 'was', 'just', 'nasty']

In [12]:
from nltk.stem.porter import PorterStemmer

In [13]:
ps= PorterStemmer()

In [14]:
print(ps.stem('doing'))
print(ps.stem('do'))

do
do


In [15]:
lst1=[]
for i in range(0,1000):
  review=re.sub('[^a-zA-Z]',' ',df['Review'][i])
  review= review.lower()
  review= review.split()
  v=[ps.stem(word) for word in review
     if not word in stopwords.words('english')]
  v= ' '.join(v)
  lst1.append(v)

In [16]:
df

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [17]:
from sklearn.feature_extraction.text import CountVectorizer


In [18]:
cv=CountVectorizer()

In [19]:
x = cv.fit_transform(lst1).toarray()

In [20]:
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [21]:
y=df['Liked'].values

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.25)

In [24]:
x_train.shape

(750, 1565)

In [25]:
x_test.shape

(250, 1565)

In [26]:
y_train.shape

(750,)

In [27]:
y_test.shape

(250,)

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [29]:
model = RandomForestClassifier(n_estimators=200)

In [30]:
model.fit(x_train,y_train)

RandomForestClassifier(n_estimators=200)

In [31]:
y_pred= model.predict(x_test)

In [32]:
print(y_pred)

[0 0 1 1 0 1 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0
 0 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1
 1 1 0 1 0 0 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 0 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0
 1 0 1 0 1 0 0 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 0 1 0 0 0 1 1 1 1 1 1 0 0
 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1 0 0 1 1 0 0 1 1 1 0 1 0 1 0 1 0 0 0 0 0 0 0
 1 1 1 0 1 1 0 1 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 1 1 0
 1 0 0 1 1 1 0 0 0 1 1 1 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0]


In [33]:
from sklearn.metrics import confusion_matrix

In [34]:
print(confusion_matrix(y_test,y_pred))

[[112  25]
 [ 37  76]]


In [35]:
correct=108+90

In [36]:
(correct/250)*100

79.2

In [37]:
# SVM

In [38]:
from sklearn.svm import SVC

In [39]:
classifier=SVC()

In [40]:
classifier.fit(x_train,y_train)

SVC()

In [41]:
pred=classifier.predict(x_test)

In [42]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [43]:
acc=accuracy_score(y_test,pred)

In [44]:
acc

0.772

In [45]:
acc*100

77.2

In [46]:
#Naive Bayes

In [47]:
from sklearn.naive_bayes import GaussianNB

In [48]:
kk=GaussianNB()

In [49]:
kk.fit(x_train,y_train)

GaussianNB()

In [50]:
pred=kk.predict(x_test)

In [51]:
acc=accuracy_score(y_test,pred)

In [52]:
acc

0.664

In [53]:
acc*100

66.4